services:
  caddy:
    image: caddy:2.8
    container_name: caddy
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 0.0.0.0:80:80/tcp
      - 0.0.0.0:443:443
    networks:
      - app
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/logs
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./html:/var/www/html # Your web directory on the host
      - ./cert:/cert

networks:
  app:
    driver: bridge
    name: app
