services:
  lib-search-server:
    image: valen/lib-search-server:latest
    container_name: lib-search-server
    labels: { com.centurylinklabs.watchtower.enable: true }
    restart: unless-stopped
    ports:
      - 7500:7500
    networks:
      - app

networks:
  app:
    external: true
