services:
  lib-search-server:
    image: cf-workers-docker-io-cuj.pages.dev/valen/lib-search-server:v1.0.0
    container_name: lib-search-server
    labels: { com.centurylinklabs.watchtower.enable: true }
    restart: unless-stopped
    ports:
      - 7500:7500
    networks:
      - app

networks:
  app:
    external: true
