services:
  lobe:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    labels: { com.centurylinklabs.watchtower.enable: true }
    restart: unless-stopped
    ports:
      - 3210:3210
    networks:
      - app
    env_file:
      - ../.env

networks:
  app:
    external: true
