services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - app
    environment:
      HOST: "0.0.0.0"
      PORT: 9000
      VERBOSE: true
      HOOKS: "/app/hooks.json"
      DEBUG: true
      URL_PREFIX: ''
      LANGUAGE: zh-CN
      TEMPLATE: true
      # HOT_RELOAD: true
      # NO_PANIC: false
      # LOG_PATH: ""
      # HTTP_METHODS: ""
      # X_REQUEST_ID: false
    env_file:
      - ../.env
    volumes:
      - ./hooks.json:/app/hooks.json:ro
      - ./scripts:/app/scripts:ro
      - ../html:/app/html

networks:
  app:
    external: true
