services:
  webdav:
    image: bytemark/webdav
    ports:
      - "5500:80"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/dav
    environment:
      - USERNAME=${WEBDAV_USERNAME}
      - PASSWORD=${WEBDAV_PASSWORD}
    networks:
      - app

networks:
  app:
    external: true
