services:
  xray:
    image: teddysun/xray
    restart: unless-stopped
    ports:
      - "11443:11443"
    volumes:
      - ./data:/etc/xray
    networks:
      - app

networks:
  app:
    external: true
