services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    # ports:
    #   - "8080:8080"
    networks:
      - app
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

networks:
  app:
    external: true
